# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-12-29 07:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djangocms_forms', '0005_formfield_field_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PUBLIC_KEY', models.CharField(blank=True, max_length=255, null=True, verbose_name='site key')),
                ('SECRET_KEY', models.CharField(blank=True, max_length=255, null=True, verbose_name='secret key')),
            ],
            options={
                'verbose_name': 'RECAPTCHA \u043d\u0430\u0441\u0442\u0440\u043e\u0439\u043a\u0438',
                'verbose_name_plural': 'RECAPTCHA \u043d\u0430\u0441\u0442\u0440\u043e\u0439\u043a\u0438',
            },
        ),
        migrations.AlterField(
            model_name='formdefinition',
            name='cmsplugin_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='djangocms_forms_formdefinition', serialize=False, to='cms.CMSPlugin'),
        ),
        migrations.AlterField(
            model_name='formdefinition',
            name='form_template',
            field=models.CharField(blank=True, choices=[(b'bootstrap_form.html', b'Bootstrap')], default='djangocms_forms/form_template/default.html', max_length=150, verbose_name='Form Template'),
        ),
    ]
